language: node_js
node_js:
  - "12"

env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.2
    - os: windows

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - yarn global add node-gyp

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      yarn build:mac
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn build:win
    else
      yarn build:linux
    fi
